# Generated by Django 3.2.5 on 2021-07-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='auth_provider',
            field=models.CharField(default='email', max_length=255),
        ),
    ]
